# Conifer ProGuard / R8 rules
#
# This file is applied on top of `proguard-android-optimize.txt` (see androidApp/build.gradle.kts).
# Most libraries used here (AndroidX, Compose, Room, kotlinx) ship their own consumer rules,
# so the rules below only cover the cases R8 cannot infer on its own.

# Keep generic signatures, annotations and exceptions so reflection-based code keeps working.
-keepattributes Signature, *Annotation*, InnerClasses, EnclosingMethod, Exceptions

# ---------------------------------------------------------------------------
# Room + bundled SQLite
# ---------------------------------------------------------------------------
# Room finds the implementation its compiler generated by *name* at runtime (Class.forName on
# "<database>_Impl"), so nothing refers to it statically and R8 would otherwise delete the whole
# generated layer, leaving the app with no database. Room's AAR ships a consumer rule covering
# the database class itself; the entities and DAOs below are the belt-and-braces part.
#
# The package is `androidx.room3`, not `androidx.room` - Room 3 renamed it. Spelled the old way
# these rules silently match nothing, which is exactly how the desktop build (whose plain jars
# can't ship consumer rules at all, unlike an AAR) ended up with no database in release.
-keep class * extends androidx.room3.RoomDatabase { <init>(); }
-keep @androidx.room3.Entity class * { *; }
-keep @androidx.room3.Dao interface *
-dontwarn androidx.room3.paging.**

# The bundled SQLite driver loads a native library and calls into it via JNI.
-keep class androidx.sqlite.driver.bundled.** { *; }
-keepclasseswithmembernames,includedescriptorclasses class androidx.sqlite.** {
    native <methods>;
}

# ---------------------------------------------------------------------------
# Kotlin / Coroutines
# ---------------------------------------------------------------------------
-keepclassmembers class kotlin.Metadata { *; }
-dontwarn kotlinx.coroutines.**
# Coroutines uses an internal volatile field updated via AtomicReferenceFieldUpdater.
-keepclassmembers class kotlinx.coroutines.internal.MainDispatcherFactory { *; }
-keepclassmembernames class kotlinx.** {
    volatile <fields>;
}

# kotlinx-datetime
-dontwarn kotlinx.datetime.**

# ---------------------------------------------------------------------------
# Napier (logging)
# ---------------------------------------------------------------------------
-dontwarn io.github.aakira.napier.**

# ---------------------------------------------------------------------------
# Compose
# ---------------------------------------------------------------------------
# Compose ships its own rules; silence warnings from optional desktop/preview-only paths.
-dontwarn androidx.compose.**