-keep class kotlinx.datetime.** { *; }
-keep class kotlinx.coroutines.swing.SwingDispatcherFactory { *; }
-keep class okio.** { *; }
-keep class sun.misc.Unsafe { *; }

# Room finds the implementation Room's compiler generated by *name* at runtime
# (Class.forName on "<database>_Impl"), so nothing refers to it statically and the shrinker
# deletes the whole generated layer - database impl, DAO impls, auto-migrations. The app then
# opens no database at all and every write silently does nothing.
#
# The package matters: this said `androidx.room` until Room 3, whose package is `androidx.room3`,
# so the rule matched nothing and the breakage was invisible until a release build was run.
-keep class * extends androidx.room3.RoomDatabase { *; }
-keep class * implements androidx.room3.RoomDatabaseConstructor { *; }

# We build our clients as `HttpClient()` without naming an engine, so Ktor picks one at
# runtime via ServiceLoader. Nothing then references the engine statically, and shrinking
# drops it while the META-INF/services entry naming it survives -- the packaged app dies
# with "Provider io.ktor.client.engine.okhttp.OkHttpEngineContainer not found". Keyed off
# the interface so a future engine swap stays covered.
-keep class * implements io.ktor.client.HttpClientEngineContainer { *; }
-keep class io.ktor.client.engine.okhttp.** { *; }

# Preserve native methods in BundledSQLiteDriverKt
-keepclasseswithmembers class androidx.sqlite.driver.bundled.** {
    native <methods>;
}

-dontwarn kotlinx.datetime.**
-dontwarn okio.**

# OkHttp reaches for TLS providers that are optional at runtime and are not on our
# classpath (we use the JDK's own provider), plus GraalVM native-image hooks we never
# run. The GraalVM ones happen to resolve when the build runs on a GraalVM JDK and not
# on the JetBrains Runtime, so silence them here rather than depend on the build JDK.
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**
-dontwarn org.graalvm.**
-dontwarn com.oracle.svm.**
