-keep class kotlinx.datetime.** { *; }
-keep class kotlinx.coroutines.swing.SwingDispatcherFactory { *; }
-keep class okio.** { *; }
-keep class sun.misc.Unsafe { *; }

# Room finds the implementation Room's compiler generated by *name* at runtime
# (Class.forName on "<database>_Impl"), so nothing refers to it statically and the shrinker
# deletes the whole generated layer - database impl, DAO impls, auto-migrations. The app then
# opens no database at all and every write silently does nothing.
#
# The package matters: this said `androidx.room` until Room 3, whose package is `androidx.room3`,
# so the rule matched nothing and the breakage was invisible until a release build was run.
-keep class * extends androidx.room3.RoomDatabase { *; }
-keep class * implements androidx.room3.RoomDatabaseConstructor { *; }

# We build our clients as `HttpClient()` without naming an engine, so Ktor picks one at
# runtime via ServiceLoader. Nothing then references the engine statically, and shrinking
# drops it while the META-INF/services entry naming it survives -- the packaged app dies
# with "Provider io.ktor.client.engine.okhttp.OkHttpEngineContainer not found". Keyed off
# the interface so a future engine swap stays covered.
-keep class * implements io.ktor.client.HttpClientEngineContainer { *; }
-keep class io.ktor.client.engine.okhttp.** { *; }

# JNA is called from the other direction: its own native dispatch library looks methods up on
# these classes by name through JNI, so nothing in the bytecode refers to them and the shrinker
# takes them out. The packaged app then dies on the first native call with
# "UnsatisfiedLinkError: Can't obtain static method fromNative(Class, Object) from class
# com.sun.jna.Native" - which nobody sees, because the one thing reaching for JNA here is KSafe
# asking the OS for somewhere safe to keep the sync password's encryption key. It catches the
# error, warns, and keeps the key Base64-encoded in a file instead. So a release build quietly
# stored its keys in the open while a `run` from Gradle used the macOS Keychain, and the only
# sign of it was one line in the log.
#
# The interfaces mapping a native library (and the structures and callbacks crossing that
# boundary) are looked up the same way, so they are kept by what they implement rather than by
# name - that covers KSafe's Keychain, DPAPI and Secret Service bindings and anything else that
# ever binds a native library this way.
-keep class com.sun.jna.** { *; }
-keep class * implements com.sun.jna.Library { *; }
-keep class * implements com.sun.jna.Callback { *; }
-keep class * extends com.sun.jna.Structure { *; }
-keepclassmembers class * extends com.sun.jna.Structure { public *; }
# jna-platform maps a great deal of Windows and X11 that this app never calls; the references
# are to classes ProGuard is right not to find on a Mac's classpath.
-dontwarn com.sun.jna.**

# Preserve native methods in BundledSQLiteDriverKt
-keepclasseswithmembers class androidx.sqlite.driver.bundled.** {
    native <methods>;
}

-dontwarn kotlinx.datetime.**
-dontwarn okio.**

# OkHttp reaches for TLS providers that are optional at runtime and are not on our
# classpath (we use the JDK's own provider), plus GraalVM native-image hooks we never
# run. The GraalVM ones happen to resolve when the build runs on a GraalVM JDK and not
# on the JetBrains Runtime, so silence them here rather than depend on the build JDK.
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**
-dontwarn org.graalvm.**
-dontwarn com.oracle.svm.**
