package eu.heha.conifer.sync

import eu.heha.conifer.model.database.Bit
import kotlinx.datetime.LocalDate
import kotlinx.datetime.LocalTime
import kotlinx.datetime.format.Padding
import kotlinx.datetime.format.char

/**
 * Renders the human-readable Markdown file for one day (Nextcloud sync spec §7.3). Pure
 * function: identical input always produces byte-identical output, which is what lets
 * competing devices converge on the readable files without any conflict handling (I6).
 */
object ReadableRenderer {

    fun render(day: LocalDate, bits: List<Bit>): String = buildString {
        append(GENERATION_NOTICE)
        append("\n\n# ")
        append(day)
        append('\n')

        val sorted = bits.sortedWith(compareBy({ it.date }, { it.id }))
        if (sorted.isEmpty()) {
            append('\n')
            append(EMPTY_DAY_MARKER)
        } else {
            for ((index, bit) in sorted.withIndex()) {
                if (index > 0) append("\n\n---\n")
                append("\n## ")
                append(TIME_FORMAT.format(bit.date.time))
                append("\n\n")
                append(bit.text)
            }
        }
        append('\n')
    }

    private const val GENERATION_NOTICE =
        "<!-- Automatically generated by Conifer. Manual changes will be overwritten. -->"
    private const val EMPTY_DAY_MARKER = "No entries on this day."

    private val TIME_FORMAT = LocalTime.Format {
        hour(Padding.ZERO)
        char(':')
        minute(Padding.ZERO)
    }
}
