import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault

/**
 * Generates the `BuildInfo` object into `commonMain`, so a running app can say which build it is:
 * the version out of [AppConfig], the commit it was built from, whether the tree was clean, and when
 * it was built. That answer is what turns a shared log or a bug report into something that can be
 * looked up - `1.2.4 (9) 29ba2459` points at one commit, "version 1.2.4" points at a month of them.
 *
 * The build time is stamped when this task runs, and this task runs when its inputs change - the
 * commit, the dirty flag or the version. So it dates the app's identity rather than the last
 * invocation of Gradle: a rebuild that produces the very same app keeps the time it first got, which
 * also keeps every `BuildInfo` consumer from recompiling on every single build.
 *
 * The generated declarations are deliberately plain `val`s and not `const val`s: a `const` is inlined
 * into whatever reads it, so a new commit would recompile all of those files instead of just this one.
 * The file is also kept import-free, so nothing it does depends on the module's opt-ins.
 */
@DisableCachingByDefault(because = "Writes one small file from values it is given; caching it across machines would import their build time")
abstract class GenerateBuildInfo : DefaultTask() {

    /** The package the object is generated into - `AppConfig.namespace`. */
    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val versionName: Property<String>

    @get:Input
    abstract val versionCode: Property<Int>

    /** The short commit hash, empty where git had no answer (see [GitCommit]). */
    @get:Input
    abstract val commit: Property<String>

    /**
     * Whether the working tree had changes that this commit does not contain (see [GitIsModified]).
     *
     * Not named `isModified`: Kotlin compiles that property's getter to `isModified()`, which
     * Gradle's task decorator reads as a plain boolean getter and refuses to implement.
     */
    @get:Input
    abstract val hasLocalChanges: Property<Boolean>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun action() {
        val packagePath = packageName.get().replace('.', '/')
        val folder = outputDirectory.get().asFile.resolve(packagePath).also { it.mkdirs() }
        folder.resolve("BuildInfo.kt").writeText(source())
    }

    private fun source(): String = """
        |// Generated by the generateBuildInfo task (see shared/build.gradle.kts) - do not edit.
        |package ${packageName.get()}
        |
        |/**
        | * Which build of the app this is, filled in at build time.
        | *
        | * [commit] is `"unknown"` where the build had no git to ask, and [isModified] says whether the
        | * working tree it was built from held changes that commit does not - a build anyone else ever
        | * runs answers false, so a true is the app admitting it cannot be looked up by hash alone.
        | */
        |object BuildInfo {
        |    val versionName: String = "${versionName.get()}"
        |
        |    val versionCode: Int = ${versionCode.get()}
        |
        |    val commit: String = "${commit.get().ifEmpty { "unknown" }}"
        |
        |    val isModified: Boolean = ${hasLocalChanges.get()}
        |
        |    /** Epoch milliseconds; `buildTime` turns it into an `Instant`. */
        |    val buildTimeMillis: Long = ${System.currentTimeMillis()}L
        |}
        |""".trimMargin()
}
