package eu.heha.conifer.sync

import eu.heha.conifer.model.database.Bit
import kotlinx.datetime.LocalDate
import kotlinx.datetime.LocalDateTime
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.time.Instant

/**
 * [ReadableRenderer] must render byte-identical output for identical input on every platform
 * (Nextcloud sync spec §7.3/§11 test case #6) — it is the whole reason competing devices never
 * need to reconcile the readable Markdown files.
 */
class ReadableRendererTest {

    private val day = LocalDate(2025, 7, 13)

    private fun bit(id: String, time: LocalDateTime, text: String) =
        Bit(id = id, text = text, createdAt = Instant.fromEpochMilliseconds(0), date = time)

    @Test
    fun renderIsDeterministicForIdenticalInput() {
        val bits = listOf(
            bit("b", LocalDateTime(2025, 7, 13, 13, 40), "second"),
            bit("a", LocalDateTime(2025, 7, 13, 8, 0), "first"),
        )

        assertEquals(ReadableRenderer.render(day, bits), ReadableRenderer.render(day, bits))
    }

    @Test
    fun renderSortsByDisplayTimeThenIdRegardlessOfInputOrder() {
        val early = bit("z", LocalDateTime(2025, 7, 13, 8, 0), "early")
        val late = bit("a", LocalDateTime(2025, 7, 13, 13, 40), "late")

        val forward = ReadableRenderer.render(day, listOf(early, late))
        val reversed = ReadableRenderer.render(day, listOf(late, early))

        assertEquals(forward, reversed)
        assertEquals(true, forward.indexOf("early") < forward.indexOf("late"))
    }

    @Test
    fun tiesOnDisplayTimeBreakOnIdAscending() {
        val second = bit("b", LocalDateTime(2025, 7, 13, 8, 0), "second")
        val first = bit("a", LocalDateTime(2025, 7, 13, 8, 0), "first")

        val rendered = ReadableRenderer.render(day, listOf(second, first))

        assertEquals(true, rendered.indexOf("first") < rendered.indexOf("second"))
    }

    @Test
    fun emptyDayRendersAPlaceholderMarker() {
        val rendered = ReadableRenderer.render(day, emptyList())

        assertEquals(
            "<!-- Automatically generated by Conifer. Manual changes will be overwritten. -->\n" +
                    "\n# 2025-07-13\n" +
                    "\nNo entries on this day.\n",
            rendered
        )
    }

    @Test
    fun rendersTheDocumentedFormat() {
        val bits = listOf(
            bit("a", LocalDateTime(2025, 7, 13, 8, 0), "Title of the post"),
            bit("b", LocalDateTime(2025, 7, 13, 13, 40), "Second post"),
        )

        assertEquals(
            "<!-- Automatically generated by Conifer. Manual changes will be overwritten. -->\n" +
                    "\n# 2025-07-13\n" +
                    "\n## 08:00\n" +
                    "\nTitle of the post\n" +
                    "\n---\n" +
                    "\n## 13:40\n" +
                    "\nSecond post\n",
            ReadableRenderer.render(day, bits)
        )
    }
}
